sprint_14_done
alexrad555/java-shareit pull request #2
Opened 2024-01-27 16:05 UTC by alexrad555

2024-01-28 08:35 UTC, ErkinKasymaliev requested changes
привет, оставил комменты!
Мне не очень нравится наличие model, который вы используете при маппингах. Зачем он вам, если можно маппить с entity в dto и наоборот без лишнего класса

2024-01-28 08:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                  @RequestHeader("X-Sharer-User-Id") Long userId) {
"X-Sharer-User-Id" -- давайте это уберем в константу

2024-01-28 08:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/mapper/StateConverter.java
> +    public BookingState convert(String source) {
это хорошо, просто уберите этот метод в BookingState без использования org.springframework.core.convert.converter.Converter

2024-01-28 08:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +
лишний отступ строки

2024-01-28 08:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
а зачем вам этот класс? у вас entity и есть dto уже

2024-01-28 08:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
вы же можете маппить с entity в dto и наоборот без лишнего класса

2024-01-28 08:35 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +
лишний отступ строки

2024-01-28 17:59 UTC, alexrad555 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
Здесь model нужен не для мэппингов. Это модель данных, с которой мы работаем на сервисном уровне. Например, в Item есть ссылки на предыдущее и следующее бронирования, которые видны только владельцу. А ещё комментарии. Держать эти сущности в ItemEntity сложнее и не очень логично.

2024-01-28 17:59 UTC, alexrad555 commented on src/main/java/ru/practicum/shareit/booking/mapper/StateConverter.java
> +    public BookingState convert(String source) {
Converter нужен, чтобы проверять корректность переданного значения enum. Не совсем понимаю, как мы заставим его использовать наш метод, если если убрать внутрь enum.

2024-01-29 04:20 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +public class Booking {
за всю свою практику я ни разу не использовал и не встречал такого подхода) Всегда и без проблем обходились entity и dto, но если вы считаете, что так лучше, то ок, без проблем

2024-01-29 04:22 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/mapper/StateConverter.java
> +    public BookingState convert(String source) {
это понятно, но можно создать public static метод в самом enum 

```
enum BookingState {
...
...

   public static BookingState convert(String s) {
    ...
   }
```

2024-01-29 04:23 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-01-29 08:42 UTC, merged